from dataclasses import dataclass
from pygame import Event as PygameEvent
from pygame import constants, mouse

import logging

@dataclass
class Event:
    handled = False

def generate_event(event: PygameEvent) -> Event:
    match event.type:
        case constants.MOUSEMOTION:
            return MouseMove(event.pos[0], event.pos[1], event.rel[0], event.rel[1])
        case constants.MOUSEBUTTONDOWN:
            return MousePress(event.pos[0], event.pos[1], event.button)
        case constants.MOUSEBUTTONUP:
            return MouseRelease(event.pos[0], event.pos[1], event.button)
        case constants.MOUSEWHEEL:
            x, y = mouse.get_pos()
            return MouseScroll(x, y, event.x, event.y)
        case constants.KEYDOWN:
            return KeyPress(event.unicode, event.key, event.mod)
        case constants.KEYUP:
            return KeyRelease(event.unicode, event.key, event.mod)
        case constants.WINDOWRESIZED:
            return WindowResize(event.size[0], event.size[1])
        case constants.WINDOWMOVED:
            return WindowMove(event.pos[0], event.pos[1])
        case constants.WINDOWCLOSE:
            return WindowClose()
        case constants.WINDOWMINIMIZED:
            return WindowMinimize()
        case constants.WINDOWMAXIMIZED:
            return WindowMaximize()
        case constants.WINDOWRESTORED:
            return WindowRestore()
        case _:
            logging.warning(f"Unknown event type: {event.type}")
            return GlobalEvent()

class GlobalEvent(Event):
    pass

class LocalEvent(Event):  # Generated by a widget and should be consumed by itself
    pass

class UniversalEvent(Event):  # Event that should be handled by all widgets
    pass

class SpreadEvent(Event):  # Event that generated by a widget and should be spread to parent widgets
    pass


@dataclass
class MouseEvent(UniversalEvent):
    x: int
    y: int

@dataclass
class MouseMove(MouseEvent):
    dx: int
    dy: int

@dataclass
class MouseButton(MouseEvent):
    button: int

class MousePress(MouseButton):
    pass

class MouseRelease(MouseButton):
    pass

@dataclass
class MouseScroll(MouseEvent):
    scrolled_x: int
    scrolled_y: int


@dataclass
class KeyEvent(GlobalEvent):
    unicode: str
    key: int
    mod: int

class KeyPress(KeyEvent):
    pass

class KeyRelease(KeyEvent):
    pass


class WindowEvent(GlobalEvent):
    pass

@dataclass
class WindowResize(WindowEvent):
    width: int
    height: int

@dataclass
class WindowMove(WindowEvent):
    x: int
    y: int

class WindowClose(WindowEvent):
    pass

class WindowMinimize(WindowEvent):
    pass

class WindowMaximize(WindowEvent):
    pass

class WindowRestore(WindowEvent):
    pass