from dataclasses import dataclass
from typing import Callable

from pygame import Event as PygameEvent
from pygame import constants, mouse

import logging

@dataclass
class Event:
    handled = False

class EventBundle(list[Event]):
    pass

pygame_events: dict[int, Callable[[PygameEvent], Event]] = {
    constants.MOUSEMOTION: lambda e: MouseMove(e.pos[0], e.pos[1], e.rel[0], e.rel[1]),
    constants.MOUSEBUTTONDOWN: lambda e: MousePress(e.pos[0], e.pos[1], e.button),
    constants.MOUSEBUTTONUP: lambda e: MouseRelease(e.pos[0], e.pos[1], e.button),
    constants.MOUSEWHEEL: lambda e: MouseScroll(mouse.get_pos()[0], mouse.get_pos()[1], e.x, e.y),
    constants.KEYDOWN: lambda e: KeyPress(e.unicode, e.key, e.mod),
    constants.KEYUP: lambda e: KeyRelease(e.unicode, e.key, e.mod),
    constants.TEXTINPUT: lambda e: TextInput(e.text),
    constants.TEXTEDITING: lambda e: TextEdit(e.text, e.start, e.length),
    constants.WINDOWRESIZED: lambda e: WindowResize(e.x, e.y),
    constants.WINDOWMOVED: lambda e: WindowMove(e.x, e.y),
    constants.WINDOWCLOSE: lambda e: WindowClose(),
    constants.WINDOWMINIMIZED: lambda e: WindowMinimize(),
    constants.WINDOWMAXIMIZED: lambda e: WindowMaximize(),
    constants.WINDOWRESTORED: lambda e: WindowRestore(),
}

def register_event_type(event_type: int, generator: Callable[[PygameEvent], Event]):
    pygame_events[event_type] = generator

def generate_event(event: PygameEvent) -> Event:
    if event.type in pygame_events:
        try:
            return pygame_events[event.type](event)
        except Exception as e:
            logging.error(f"Error generating event for Pygame event {event}: {e}")
    logging.warning(f"Returned an empty Event because unrecognized Pygame event provided: {event}")
    return Event()

class GlobalEvent(Event):
    pass

class LocalEvent(Event):  # Generated by a widget and should be consumed by itself
    pass

class UniversalEvent(Event):  # Event that should be handled by all widgets
    pass

class SpreadEvent(Event):  # Event that generated by a widget and should be spread to parent widgets
    pass


@dataclass
class MouseEvent(Event):
    x: int
    y: int

@dataclass
class MouseMove(MouseEvent, UniversalEvent):
    dx: int
    dy: int

@dataclass
class MouseButton(MouseEvent, GlobalEvent):
    button: int

class MousePress(MouseButton):
    pass

class MouseRelease(MouseButton):
    pass

@dataclass
class MouseScroll(MouseEvent, GlobalEvent):
    scrolled_x: int
    scrolled_y: int


@dataclass
class KeyEvent(GlobalEvent):
    unicode: str
    key: int
    mod: int

class KeyPress(KeyEvent):
    pass

class KeyRelease(KeyEvent):
    pass


class WindowEvent(GlobalEvent):
    pass

@dataclass
class TextEvent(GlobalEvent):
    text: str

@dataclass
class TextEdit(TextEvent):
    start: int
    length: int

class TextInput(TextEvent):
    pass

@dataclass
class WindowResize(WindowEvent):
    width: int
    height: int

@dataclass
class WindowMove(WindowEvent):
    x: int
    y: int

class WindowClose(WindowEvent):
    pass

class WindowMinimize(WindowEvent):
    pass

class WindowMaximize(WindowEvent):
    pass

class WindowRestore(WindowEvent):
    pass